version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: manage_cuentas
    volumes:
      - postgres-data:/var/lib/postgresql/data
      
  person-service:
    build:
      context: ./person-service
      dockerfile: Dockerfile
    image: person-service:1.0
    container_name: person-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/manage_cuentas
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
      - IS_DOCKER=true

  movement-service:
    build:
      context: ./movement-service
      dockerfile: Dockerfile
    image: movement-service:1.0
    container_name: movement-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/manage_cuentas
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
      - IS_DOCKER=true

volumes:
  postgres-data:
